name: Sync with Upstream
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Add Upstream
        run: git remote add upstream https://github.com/dnakov/anon-kode.git || true
      - name: Fetch Upstream
        run: git fetch upstream
      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

